import random
print('Seja Bem vindo a losvenia.')
print('um pais que fica localizado entre a divisa de um mundo real e fantasioso, onde varias criaturas perigosas residem ')
nome=input('qual o seu nome brava criatura? ')
print ('Humano, Elfo, Anao, Orc')
raca=input(f'{nome} escolha uma dessas raças acima:')
print(f'vejo que você é um {raca}')
print('Guerreiro, Mago, Ladino, Clérico')
classe=input('escolha uma das classes acima: ')
print(f'entao você é da classe {classe}')
forca=random.randint(1,20)
destreza=random.randint(1,20)
constituicao=random.randint(1,20)
inteligencia=random.randint(1,20)
sabedoria=random.randint(1,20)
carisma=random.randint(1,20)
print('Essas sao as caracteristicas de um Humano: ')
print(f'força: {forca}')
print(f'destreza: {destreza}')
print(f'constituiçao: {constituicao}')
print(f'inteligencia: {inteligencia}')
print(f'sabedoria: {sabedoria}')
print(f'carisma: {carisma}')
pv=10+(constituicao//2)+5
iniciativa=destreza//2-5
cargamaxima=forca*5
print('='*20)
print('  FICHA DO HEROI  ')
print('='*20)
print(f'Nome do Heroi: {nome}')
print(f'Raça: {raca}')
print(f'Classe {classe}')
print('----- ATRIBUTOS-----')
print(f'Força: {forca}')
print(f'destreza: {destreza}')
print(f'constituiçao: {constituicao}')
print(f'inteligencia: {inteligencia}')
print(f'sabedoria: {sabedoria}')
print(f'carisma: {carisma}')
print('-----DERIVADOS-----')
print(f'PV: {pv}')
print(f'Iniciativa: {iniciativa}')
print(f'cargamaxima: {cargamaxima}')
print('='*20)